In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('seaborn')
df = pd.read_csv('./dataset/25 Sep 2020 finviz.csv')

In [2]:
df.loc[df['Ticker'] == 'AAPL' ]

,No.,Ticker,Company,Sector,Industry,Country,Market Cap,P/E,Forward P/E,PEG,...,Average Volume,Relative Volume,Price,Change,Volume,Earnings Date,Target Price,IPO Date,After-Hours Close,After-Hours Change
13,14,AAPL,Apple Inc.,Technology,Consumer Electronics,USA,1983179.16,34.14,29.02,2.74,...,172825.79,0.86,112.28,3.75%,149468433,7/30/2020 4:30:00 PM,118.39,12/12/1980,112.04,-0.21%

In [3]:
#function to remove %
def pct_remove(value1):
    if '%' in str(value1):
        value1 = value1.replace('%','')
    return value1

In [4]:
    df['50-Day Simple Moving Average']=df['50-Day Simple Moving Average'].map(pct_remove)
    df['50-Day Simple Moving Average']=df['50-Day Simple Moving Average'].astype('float64')
    df['50-Day Simple Moving Average']=df['50-Day Simple Moving Average']/100

In [13]:
    df['200-Day Simple Moving Average']=df['200-Day Simple Moving Average'].map(pct_remove)
    df['200-Day Simple Moving Average']=df['200-Day Simple Moving Average'].astype('float64')
    df['200-Day Simple Moving Average']=df['200-Day Simple Moving Average']/100

In [5]:
    df['Change']=df['Change'].map(pct_remove)
    df['Change']=df['Change'].astype('float64')
    df['Change']=df['Change']/100

In [6]:
df.loc[df['Ticker'] == 'AAPL' ]

,No.,Ticker,Company,Sector,Industry,Country,Market Cap,P/E,Forward P/E,PEG,...,Average Volume,Relative Volume,Price,Change,Volume,Earnings Date,Target Price,IPO Date,After-Hours Close,After-Hours Change
13,14,AAPL,Apple Inc.,Technology,Consumer Electronics,USA,1983179.16,34.14,29.02,2.74,...,172825.79,0.86,112.28,0.0375,149468433,7/30/2020 4:30:00 PM,118.39,12/12/1980,112.04,-0.21%

In [7]:
df['50 sma price'] = (df['Price']) / (1 +df['50-Day Simple Moving Average'] )

In [16]:
df['prev close'] = (df['Price']) / (1 + df['Change'] )
df['change value'] = df['prev close'] * df['Change']

In [11]:
df.loc[df['Ticker'] == 'AAPL' ]

,No.,Ticker,Company,Sector,Industry,Country,Market Cap,P/E,Forward P/E,PEG,...,Price,Change,Volume,Earnings Date,Target Price,IPO Date,After-Hours Close,After-Hours Change,50 sma price,change 2
13,14,AAPL,Apple Inc.,Technology,Consumer Electronics,USA,1983179.16,34.14,29.02,2.74,...,112.28,0.0375,149468433,7/30/2020 4:30:00 PM,118.39,12/12/1980,112.04,-0.21%,111.610338,4.2105

In [14]:
df['200 sma price'] = (df['Price']) / (1 +df['200-Day Simple Moving Average'] )

In [15]:
df.loc[df['Ticker'] == 'AAPL' ]

,No.,Ticker,Company,Sector,Industry,Country,Market Cap,P/E,Forward P/E,PEG,...,Change,Volume,Earnings Date,Target Price,IPO Date,After-Hours Close,After-Hours Change,50 sma price,change 2,200 sma price
13,14,AAPL,Apple Inc.,Technology,Consumer Electronics,USA,1983179.16,34.14,29.02,2.74,...,0.0375,149468433,7/30/2020 4:30:00 PM,118.39,12/12/1980,112.04,-0.21%,111.610338,4.2105,85.112189